### SEARX.ENVS.NET - local ###
server {
	include snippets/listen_local.conf;
	include snippets/listen.conf;
	server_name searx.envs.net;

	return 307 https://searx.envs.net$request_uri;
}

server {
	include snippets/listen_local_ssl.conf;
	include snippets/listen_ssl.conf;
#	include snippets/ddos_def.conf;
	http2 on;
	server_name searx.envs.net;

	include snippets/ssl.conf;
	include ssl/envs_net_wild.conf;
	include snippets/local_ssl_header.conf;

	error_log /var/log/nginx/searx.envs.net-error.log crit;

	root /usr/local/searxng;

	location / {
		uwsgi_pass unix:///usr/local/searxng/run/socket;

		include uwsgi_params;

		uwsgi_param    HTTP_HOST             $host;
		uwsgi_param    HTTP_CONNECTION       $http_connection;

		# see flaskfix.py
		uwsgi_param    HTTP_X_SCHEME         $scheme;
		uwsgi_param    HTTP_X_SCRIPT_NAME    /searxng;

		# see limiter.py
		uwsgi_param    HTTP_X_REAL_IP        $remote_addr;
		uwsgi_param    HTTP_X_FORWARDED_FOR  $proxy_add_x_forwarded_for;
	}
}

#ALIAS
server {
	include snippets/listen.conf;
	server_name search.envs.net;

	return 301 https://searx.envs.net$request_uri;
}

server {
	include snippets/listen_ssl.conf;
	server_name search.envs.net;

	include snippets/ssl.conf;
	include ssl/envs_net_wild.conf;
	include snippets/local_ssl_header.conf;

	return 301 https://searx.envs.net$request_uri;
}
