#!/bin/bash

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && command -v lsb_release >/dev/null; then
    DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf 'System information from %s\n\n' "$(date +'%A, %d.%m.%Y - %H:%M:%S %Z')"
printf "   %s (%s %s %s)\n" \
    "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"

printf '   Uptime:\t%s\n' "$(uptime -p)"

awk '{ printf "   load:\t%s %s %s\n", $1, $2, $3 }' /proc/loadavg

awk '
/^MemTotal:/ { printf "   MemTotal:\t%s %s\n", $2, $3 }
/^MemFree:/  { printf "   MemFree:\t%s %s\n", $2, $3 }
' /proc/meminfo

df -h --output=target,size,used,avail,pcent / /home | awk '
NR==1 { next }
BEGIN {
    printf "   disk space:  %-8s %7s | %7s | %7s\n", "(mount)", "total", "used", "free"
}
{
    printf "                %-8s %7s | %7s | %7s (%s)\n", $1, $2, $3, $4, $5
}
'

printf '   processes:\t%s\n' "$(ps ax --no-headers | wc -l)"

zombies=$(ps axo stat= | awk '$1 ~ /^Z/ { c++ } END { print c+0 }')
if [ "$zombies" -gt 0 ]; then
    printf '\n   => There are %s zombie processes.\n' "$zombies"
fi

printf '\n'
