#!/bin/bash

cat << EOM

cool things to do while you're here on envs.net:

* envs        - manage your users_info.json entrys and user-submitted scripts
* pb          - command line pastebin
* who         - see who else is connected right now
* finger      - get info on other users (local and remote)
* mutt        - default @envs.net command line mail client
* clinte      - community notices system
* bbj         - forum - command line bbs (bulletin butter and jelly)
* twtxt       - minimalist microblogging service - see twtxt --help
* toot        - a command-line fediverse client
* weechat     - the extensible irc chat client
                weechat-activate-matrix.sh - to activate the matrix-chat plugin
* webirc      - add your web-irc-chat account for our thelounge
* gomuks      - a terminal based matrix client written in go
* todo-txt    - simple todo managing
* burrow      - manage your gopherhole - try burrow -h to see the options
* hole        - open our envs.net gopherhole
* feels       - ttbp feels engine
                post to local feels, somewhere on your site, or gopher.
  or bb       - bashblog - see https://help.envs.net/blog/#with-bashblog
* linkulator  - a link aggregator - gopher://envs.net/1/linkulator/
* botany      - tend to your plants and visit teammates' gardens
* sl          - spacelaunch: check sl -h for more info
* dcss        - connect to crawl.tildeverse.org with ssh to play
                dungeon crawl: stone soup

for more information, check out:
  * man envs.net
  * https://help.envs.net/

or type motd to see this message again.

###

EOM
