#!/bin/bash

printf 'users online: %s | total: %s\n' "$(users | tr ' ' \\n | uniq | wc -l)" "$(ls /home | wc -l)"
printf 'allocated ttys: %s\n\n' "$(users | wc -w)"

users | tr ' ' \\n | uniq | column

printf '\n###\n'
